name: Python Format and MyPy Check

on:
  push:
    paths:
      - 'server/**'

jobs:
  format_and_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy
        pip install -r server/requirements.txt

    - name: Format code with Black
      run: black server

    - name: Check code with MyPy
      run: mypy server
